Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

urlpatterns = [ 
	url(r'^nuevo_curso$',views.Nuevo_curso, name="nuevo_curso"),
	url(r'^lista_cursos$',views.Lista_cursos, name="lista_cursos"),
	url(r'^detalle/(?P<curso_nombre>.*)$',views.Detalle_curso, name="detalle_curso"),
	url(r'^modificar/(?P<curso_nombre>.*)$',views.Modificar_curso, name="modificar_curso"),
	url(r'^mis_cursos/$',views.Mis_cursos, name="mis_cursos"),
	url(r'^eliminar_curso/(?P<pk>[0-9]+)/$', views.Eliminar_curso, name="eliminar_curso"),
	]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/',include('empresa.urls',namespace='empresa')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos')),
    url(r'^practicas/',include('practicas.urls', namespace='practicas')),
    url(r'^buscar_zona/$',views.buscar_zona, name ='buscar'),
    url(r'^buscar_zona/(?P<zona>.*)$',views.listar_zona, name='listar_zona'),
    url(r'^buscar_empresa/$',views.buscar_empresa, name='buscar_empresa'),
    url(r'^buscar_tematica/$',views.buscar_tematica, name='buscar_tematica'),
    url(r'^$',views.index, name='index'),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from empresa.models import Empresa
# Create your models here.

@python_2_unicode_compatible
class Curso(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion = models.TextField()
	empresa = models.ForeignKey(Empresa)
	horas = models.PositiveIntegerField()
	inicio= models.DateField()
	final = models.DateField()
	precio = models.PositiveIntegerField()
	zona = models.CharField(max_length=50)
	target = models.TextField()

	def __str__(self):
		return self.nombre

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from empresa.models import Empresa
from .models import Curso
from django.contrib.auth.decorators import login_required
from .form import NuevoCursoForm, ModificarCursoForm

# Create your views here.

@login_required(login_url="/empresa/login")
def Nuevo_curso(request):
	if request.method== 'POST':
		form = NuevoCursoForm(request.POST)
		if form.is_valid():
			empresa_aux=get_object_or_404(Empresa, username=request.user.username)
			nuevo_curso= Curso()
			nuevo_curso.nombre=request.POST['nombre']
			nuevo_curso.descripcion=request.POST['descripcion']
			nuevo_curso.horas = request.POST['horas']
			nuevo_curso.inicio = request.POST['inicio']
			nuevo_curso.final= request.POST['final']
			nuevo_curso.precio = request.POST['precio']
			nuevo_curso.zona =request.POST['zona']
			nuevo_curso.target = request.POST['target']

			nuevo_curso.empresa=empresa_aux

			nuevo_curso.save()

			return redirect("/cursos/mis_cursos")
	else:
		form = NuevoCursoForm()
	context= {'form':form}
	return render(request,'cursos/NuevoCurso.html', context)


def Lista_cursos(request):
	list_cursos = Curso.objects.all().order_by('inicio')
	if len(list_cursos) == 0:
		msg="No hay cursos en estos momentos"
	else:
		msg="Hay cursos disponibles ahora mismo"
	context={'msg':msg, 'list_cursos':list_cursos }
	return render(request,'cursos/Lista_cursos.html',context)

def Detalle_curso(request,curso_nombre):
	curso = get_object_or_404(Curso, nombre=curso_nombre)
	return render(request,"cursos/Detalle_curso.html",{'curso':curso})

@login_required(login_url="/empresa/login")
def Modificar_curso(request, curso_nombre):
	curso = get_object_or_404(Curso, nombre=curso_nombre)
	if curso.empresa.username == request.user.get_username():
		if request.method == 'POST':
			form = ModificarCursoForm(request.POST, instance=curso)
			if form.is_valid():
				form.save()
				return redirect("/cursos/mis_cursos")
		else:
			form = ModificarCursoForm(instance=curso)
		context={'form': form, 'curso':curso}
		return render(request, "cursos/Modificar_curso.html",context)

	else:
		return HttpResponse("No es tu curso, no se modifica")

@login_required(login_url="/empresa/login")
def Mis_cursos(request):
	empresa_aux=Empresa.objects.get(username=request.user.get_username())
	list_cursos = Curso.objects.filter(empresa=empresa_aux).order_by('inicio')
	if len(list_cursos) == 0:
		msg="No ofreces cursos en estos momentos"
	else:
		msg="Ofreces estos cursos ahora mismo"
	context={'msg':msg, 'list_cursos':list_cursos }
	return render(request,'cursos/Lista_cursos_empresa.html',context)


@login_required(login_url="/empresa/login")
def Eliminar_curso(request, pk):
	curso=get_object_or_404(Curso,pk=pk)
	if curso.empresa.username == request.user.get_username(): 
		if request.method == 'POST':
			curso.delete()
			return redirect("/cursos/mis_cursos")
		else:
			return render(request,'cursos/Eliminar_curso.html',{'curso':curso})
	else:
		return HttpResponse("Este no es tu curso")

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/Detalle_curso.html
{% extends "baseTemplateCursos.html" %}
{% block tittle %}{{curso.nombre}{% endblock %}

{% block mainText %}
<p>Empresa: {{curso.empresa.nombre}}</p>
<p>Descripcion: {{curso.descripcion}}</p>

<p>Desde el {{curso.inicio}} hasta el {{curso.final}}  </p>
<p>Zona de trabajo: {{curso.zona}}</p>
<p>Precio: {{curso.precio}} euros</p>
<p>Publico recomendado: {{curso.target}}</p>


<p>Contactos de la empresa:
<ul>-Telefono: {{curso.empresa.telefono}}</ul>
<ul>-Email: {{curso.empresa.email}}
</ul>
</p>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/Eliminar_curso.html
{% extends "baseTemplateCursos.html" %}



{% block title %}Borrar curso {{curso.nombre}} {% endblock %}

{% block mainText %}
<form id='form' method='POST'>{% csrf_token %}
<p>¿Seguro que desea borrar el curso?<input type="submit" name="Borrar"></p>
</form>

{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/Lista_cursos.html
{% extends "baseTemplateCursos.html" %}
{% block title %}Lista cursos{% endblock %}
<h1>Cursos que se ofertan actualmente. Clicke para modificarlos</h1>

{% block mainText %}
<p>Los cursos se ordenan por fecha de inicio</p>
<p>{{msg}}</p>

<ul>
{% for curso in list_cursos %}
	<li><a href="{% url 'cursos:detalle_curso' curso.nombre %}">{{curso.nombre}}</a>({{curso.empresa}}): {{curso.descripcion}}</li>
{% endfor %}
</ul>	



{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/Lista_cursos_empresa.html
{% extends "baseTemplateCursos.html" %}
{% block title %}Mis cursos{% endblock %}
{% block mainText %}
<h1>Cursos que oferta actualmente. Pinche para modificarlos</h1>

<p>Los cursos se ordenan por fecha de inicio</p>
<a href="{% url 'cursos:nuevo_curso' %}">Añadir curso</a>

<p>{{msg}}</p>

<ul>

{% for curso in list_cursos %}
	<li><a href="{% url 'cursos:modificar_curso' curso.nombre %}">{{curso.nombre}}</a>: {{curso.descripcion}}</li>
{% endfor %}
</ul>	



{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/Modificar_curso.html
{% extends "baseTemplateCursos.html" %}

{% block title %}Modificando el curso {{curso.nombre}}{% endblock %}

{% block mainText %}IMPORTANTE: las fechas deben introducirse en formato YYYY-MM-DD ---> Ejemplo: 2016-01-01

	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
	{{ form.as_p }}	
	<p><input type="submit" name="Submit"></p>
	
	</form>


	</p>

<a href="{% url 'cursos:eliminar_curso' curso.pk %}">Borrar curso</a>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/templates/cursos/NuevoCurso.html
{% extends "baseTemplateCursos.html" %}

{% block title %}Nuevo curso{% endblock %}

{% block mainText %}IMPORTANTE: las fechas deben introducirse en formato YYYY-MM-DD ---> Ejemplo: 2016-01-01
	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" name="Submit"></p>
	</form>


	</p>
{% endblock %}