Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

urlpatterns = [ 
	url(r'^nuevo_curso$',views.Nuevo_curso, name="nuevo_curso"),
	url(r'^lista_cursos$',views.Lista_cursos, name="lista_cursos"),
	url(r'^detalle/(?P<curso_nombre>.*)$',views.Detalle_curso, name="detalle_curso"),
	url(r'^modificar/(?P<curso_nombre>.*)$',views.Modificar_curso, name="modificar_curso"),
	url(r'^mis_cursos/$',views.Mis_cursos, name="mis_cursos"),
	url(r'^eliminar_curso/(?P<pk>[0-9]+)/$', views.Eliminar_curso, name="eliminar_curso"),
	]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/',include('empresa.urls',namespace='empresa')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos')),
    url(r'^practicas/',include('practicas.urls', namespace='practicas')),
    url(r'^buscar_zona/$',views.buscar_zona, name ='buscar'),
    url(r'^buscar_zona/(?P<zona>.*)$',views.listar_zona, name='listar_zona'),
    url(r'^buscar_empresa/$',views.buscar_empresa, name='buscar_empresa'),
    url(r'^buscar_tematica/$',views.buscar_tematica, name='buscar_tematica'),
    url(r'^$',views.index, name='index'),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from practicas.views import Nueva_practica
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^nueva_practica$', views.Nueva_practica, name="nueva_practica"),
	url(r'^detalle/(?P<pk>[0-9]+)/$',views.Detalle_practica.as_view(), name="detalle_practica"),
	url(r'^lista_practicas$', views.Lista_practicas.as_view(), name="lista_practicas"),
	url(r'^modificar/(?P<pk>[0-9]+)/$',login_required(views.Modificar_practica), name="modificar_practica"),
	url(r'^mis_practicas$', login_required(views.Mis_practicas.as_view()), name="mis_practicas"),
	url(r'^eliminar_practica/(?P<pk>[0-9]+)/$',views.Eliminar_practica, name="eliminar_practica"),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/models.py
from __future__ import unicode_literals
from empresa.models import Empresa
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Practica(models.Model):
	nombre = models.CharField(max_length=50)
	descripcion= models.TextField()
	empresa = models.ForeignKey(Empresa)
	remuneracion = models.PositiveIntegerField()
	horas_semana = models.PositiveIntegerField()
	dias_trabajo = models.PositiveIntegerField()
	zona = models.CharField(max_length=50)
	target= models.TextField()
	duracion = models.PositiveIntegerField()

	def __str__(self):
		return self.nombre

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Practica
from empresa.models import Empresa
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView


from .form import NuevaPracticaForm, ModificarPracticaForm
# Create your views here.

@login_required()
def Nueva_practica(request):
	if request.method == 'POST':
		form = NuevaPracticaForm(request.POST)
		if form.is_valid():
			empresa_aux=get_object_or_404(Empresa, username=request.user.username)
			nueva_practica = Practica()
			nueva_practica.nombre=request.POST['nombre']
			nueva_practica.descripcion=request.POST['descripcion']
			nueva_practica.empresa=empresa_aux
			nueva_practica.remuneracion=request.POST['remuneracion']
			nueva_practica.horas_semana = request.POST['horas_semana']
			nueva_practica.dias_trabajo = request.POST['dias_trabajo']
			nueva_practica.zona = request.POST['zona']
			nueva_practica.target = request.POST['target']
			nueva_practica.duracion = request.POST['duracion']
			nueva_practica.save()
			return redirect("/practicas/mis_practicas")
	else:
		form = NuevaPracticaForm()
	context= {'form':form}
	return render(request, 'practicas/NuevaPractica.html',context)
	
class Lista_practicas(ListView):
	model= Practica
	template_name='practicas/Lista_practicas.html'
	context_object_name = 'practicas_list'
	def get_queryset(self):
		return Practica.objects.all()



class Detalle_practica(DetailView):
	model = Practica
	template_name='practicas/Detalle_practica.html'

def Modificar_practica(request, pk):
	practica=get_object_or_404(Practica,pk=pk)
	if practica.empresa.username==request.user.get_username():
		if request.method == 'POST':
			form = ModificarPracticaForm(request.POST, instance=practica)
			if form.is_valid():
				form.save()
				return redirect("/practicas/mis_practicas")
		else:
			form = ModificarPracticaForm(instance=practica)
		context={'form':form, 'practica':practica}
		return render(request,"practicas/practica_update_form.html",context)
	else:
		return HttpResponse("No es tu practica, no se modifica")

class Mis_practicas(ListView):
	model= Practica
	template_name='practicas/Lista_practicas_empresa.html'
	context_object_name='practicas_list'
	def get_queryset(self):
		empresa=self.request.user
		return Practica.objects.filter(empresa=empresa)


@login_required()
def Eliminar_practica(request, pk):
	practica=get_object_or_404(Practica,pk=pk)
	if practica.empresa.username == request.user.get_username():
		if request.method == 'POST':
			practica.delete()
			return redirect("/practicas/mis_practicas")
		else:
			return render(request, "practicas/Eliminar_practica.html",{'practica':practica})
	else:
		return HttpResponse("Este no es tu practica")

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/Detalle_practica.html
{% extends "baseTemplatePractica.html" %}
{% block tittle %}{{object.nombre}{% endblock %}

{% block mainText %}
<p>Nombre: {{object.nombre}}</p>
<p>Empresa: {{object.empresa.nombre}}</p>
<p>Descripcion: {{object.descripcion}}</p>

<p>Duracion: {{object.duracion}}  meses</p>
<p>Horas semanales: {{object.horas_semana}}</p>
<p>Dias de trabajo a la semana: {{object.dias_trabajo}}</p>
<p>Zona de trabajo: {{object.zona}}</p>
<p>Sueldo: {{object.remuneracion}} euros</p>
<p>Titulos buscados: {{object.target}}</p>


<p>Contactos de la empresa:
<ul>-Telefono: {{object.empresa.telefono}}</ul>
<ul>-Email: {{object.empresa.email}}
</ul>
</p>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/Eliminar_practica.html
{% extends "baseTemplatePractica.html" %}
{% block title %}Borrando practica {{practica.nombre}}{% endblock %}
{% block mainText %}

<form id='form' method='POST'>{% csrf_token %}
	<p>¿Esta seguro de que desea borrar {{practica.nombre}}?</p>
	<input type="submit" name="Borrar">
</form>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/Lista_practicas.html
{% extends "baseTemplatePractica.html" %}
{% block title %}Lista practicas{% endblock %}
<h1>Cursos que se ofertan actualmente. Clicke para modificarlos</h1>

{% block mainText %}
{% if practicas_list %}
	Las practicas activas son:
{% else %}
	No tiene practicas activas
{% endif %}

<ul>
{% for practica in practicas_list %}
	<li><a href="{% url 'practicas:detalle_practica' practica.pk %}">{{practica.nombre}}</a>({{practica.empresa}}): {{practica.descripcion}}</li>
{% endfor %}
</ul>	



{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/Lista_practicas_empresa.html
{% extends "baseTemplatePractica.html" %}
{% block title %}Lista practicas{% endblock %}

{% block mainText %}
<h1>Practicas que se ofertan actualmente. Pinche para modificarlas</h1>

{% if practicas_list %}
	Sus practicas activas son:
{% else %}
	No tiene practicas activas.
{% endif %}
<a href="{% url 'practicas:nueva_practica' %}"><br>Añadir practica</a>
<ul>
{% for practica in practicas_list %}
	<li><a href="{% url 'practicas:modificar_practica' practica.pk %}">{{practica.nombre}}</a>: {{practica.descripcion}}</li>
{% endfor %}
</ul>	



{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/NuevaPractica.html
{% extends "baseTemplatePractica.html" %}

{% block title %}Nuevo practica{% endblock %}

{% block mainText %}La duracion es en meses y la remuneracion en euros/mes
	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" name="Submit"></p>
	</form>


	</p>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/templates/practicas/practica_update_form.html
{% extends "baseTemplatePractica.html" %}
{% block title %}Modificando la practica {{practica.nombre}}{% endblock %}
{% block mainText %}La duracion es en meses y la remuneracion en euros/mes
	<a href="{% url 'practicas:eliminar_practica' practica.pk %}"><br>Eliminar practica</a>

	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" name="Submit"></p>
	</form>
	</p>
{% endblock %}