Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

urlpatterns = [ 
	url(r'^nuevo_curso$',views.Nuevo_curso, name="nuevo_curso"),
	url(r'^lista_cursos$',views.Lista_cursos, name="lista_cursos"),
	url(r'^detalle/(?P<curso_nombre>.*)$',views.Detalle_curso, name="detalle_curso"),
	url(r'^modificar/(?P<curso_nombre>.*)$',views.Modificar_curso, name="modificar_curso"),
	url(r'^mis_cursos/$',views.Mis_cursos, name="mis_cursos"),
	url(r'^eliminar_curso/(?P<pk>[0-9]+)/$', views.Eliminar_curso, name="eliminar_curso"),
	]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/',include('empresa.urls',namespace='empresa')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos')),
    url(r'^practicas/',include('practicas.urls', namespace='practicas')),
    url(r'^buscar_zona/$',views.buscar_zona, name ='buscar'),
    url(r'^buscar_zona/(?P<zona>.*)$',views.listar_zona, name='listar_zona'),
    url(r'^buscar_empresa/$',views.buscar_empresa, name='buscar_empresa'),
    url(r'^buscar_tematica/$',views.buscar_tematica, name='buscar_tematica'),
    url(r'^$',views.index, name='index'),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^registro$',views.Registro,name="registro"),
	url(r'^agregado$',views.Agregado,name="agreagado"),
	url(r'^login$',views.Login, name="login"),
	url(r'^logout$',views.Logout, name="logout"),
	url(r'^already_loged$',views.Already_loged, name="already_loged"),
	url(r'^not_loged$',views.Not_loged, name="not_loged"),
	url(r'^mi_empresa$',views.Mi_empresa, name='mi_empresa'),
	url(r'^detalle/(?P<pk>[0-9]+)/$', views.Detalle_empresa, name="detalle_empresa"),
	url(r'^modificar_mi_empresa$',views.Modificar_mi_empresa, name="modificar_mi_empresa"),
	url(r'^modificar_mi_contrasenia$',views.Cambiar_contrasenia, name="modificar_mi_contrasenia"),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from practicas.views import Nueva_practica
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^nueva_practica$', views.Nueva_practica, name="nueva_practica"),
	url(r'^detalle/(?P<pk>[0-9]+)/$',views.Detalle_practica.as_view(), name="detalle_practica"),
	url(r'^lista_practicas$', views.Lista_practicas.as_view(), name="lista_practicas"),
	url(r'^modificar/(?P<pk>[0-9]+)/$',login_required(views.Modificar_practica), name="modificar_practica"),
	url(r'^mis_practicas$', login_required(views.Mis_practicas.as_view()), name="mis_practicas"),
	url(r'^eliminar_practica/(?P<pk>[0-9]+)/$',views.Eliminar_practica, name="eliminar_practica"),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/views.py
from django.shortcuts import render, redirect
from .form import BuscarZonaForm, BuscarEmpresaForm, BuscarTematicaForm
from django.http import HttpResponse
from cursos.models import Curso
from practicas.models import Practica
from empresa.models import Empresa

def index(request):
	return render(request,'djangoPW/index.html')


def buscar_zona(request):
	if request.method == 'POST':
		form = BuscarZonaForm(request.POST)
		if form.is_valid():
			zona=request.POST['zona']
			url='/buscar_zona/'+str(zona)
			return redirect(url)
	else:
		form = BuscarZonaForm()
	context={'form':form}
	return render(request,'djangoPW/Buscar_zona.html',context)

def listar_zona(request, zona):
	lista_curso=Curso.objects.filter(zona__icontains=zona)
	lista_practica=Practica.objects.filter(zona__icontains=zona)
	context={'lista_curso':lista_curso, 'lista_practica':lista_practica,'zona':zona}
	return render(request,'djangoPW/Lista_zona.html',context)

def buscar_empresa(request):
	if request.method == 'POST':
		form=BuscarEmpresaForm(request.POST)
		if form.is_valid():
			empresa=request.POST['empresa']
			lista_empresas=Empresa.objects.filter(nombre__icontains=empresa)
			return render(request,'djangoPW/Listar_empresas.html',{'empresa':empresa,'lista_empresas':lista_empresas})
	else:
		form=BuscarEmpresaForm()
	context={'form':form}
	return render(request,'djangoPW/Buscar_empresa.html',context)

def buscar_tematica(request):
	if request.method == 'POST':
		form=BuscarTematicaForm(request.POST)
		if form.is_valid():
			tema=request.POST['tema']
			lista_cursos=Curso.objects.filter(descripcion__icontains=tema)
			lista_practicas=Practica.objects.filter(descripcion__icontains=tema)
			context={'tema':tema,'lista_cursos':lista_cursos,'lista_practicas':lista_practicas}
			return render(request,'djangoPW/Listar_tematica.html',context)
	else:
		form=BuscarTematicaForm()
	context={'form':form}
	return render(request,'djangoPW/Buscar_tematica.html',context)

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Buscar_empresa.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}
<form id='form' method="POST" enctype="multipart/form-data">{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" name="Buscar empresas">

	
</form>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Buscar_tematica.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}

<form id="form" method='POST' enctype="multipart/form-data">{% csrf_token %}
{{form.as_p}}
<input type="submit" name="Buscar">
</form>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Buscar_zona.html
{% extends "baseDocumentTemplate.html" %}


{% block content %}

<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
	{{ form.as_p }}
	<p><input type="submit" name="Buscar"></p>

</form>


{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Lista_zona.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}

<p>Cursos:</p>
{% if lista_curso|length %}
	{% for curso in lista_curso %}
		<ul><a href="{% url 'cursos:detalle_curso' curso.nombre %}">{{curso.nombre}}</a></ul>
	{% endfor %}
{% else %}
	<p>No hay cursos en {{zona}}</p>
{% endif %}

<p>Practicas:</p>
{% if lista_practica|length %}
	{% for practica in lista_practica %}
		<ul><a href="{% url 'practicas:detalle_practica' practica.pk %}">{{practica.nombre}}</a></ul>
	{% endfor %}
{% else %}
	<p>No hay practicas en {{zona}}</p>
{% endif %}


{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Listar_empresas.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}
<p>Empresas que contienen "{{empresa}}":<br></p>
{% if lista_empresas|length %}
	{% for emp in lista_empresas %}
		<ul><a href="{% url 'empresa:detalle_empresa' emp.pk %}">{{emp.nombre}}</a></ul>
	{% endfor %}
{% else %}
	<p>No hay empresas con ese nombre</p>
{% endif %}

{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/Listar_tematica.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}

<p>Tema: {{tema}}</p>

<p><br>Cursos:</p>
{% if lista_cursos %}
	{% for curso in lista_cursos %}
		<ul><a href="{% url 'cursos:detalle_curso' curso.nombre %}">{{curso.nombre}}({{curso.empresa.nombre}})</a></ul>
	{% endfor %}
{% else %}	
	<p>No hay cursos de esta tematica</p>
{% endif %}

<p><br>Practicas:</p>
{% if lista_practicas %}
	{% for practica in lista_practicas %}
		<ul><a href="{% url 'practicas:detalle_practica' practica.pk %}">{{practica.nombre}}({{practica.empresa.nombre}})</a></ul>
	{% endfor %}
{% else %}	
	<p>No hay cursos de esta tematica</p>
{% endif %}


{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/templates/djangoPW/index.html
{% extends "baseDocumentTemplate.html" %}

{% block content %}
<li><a href="/cursos/lista_cursos">Cursos</a></li>
<li><a href="/practicas/lista_practicas">Practicas</a></li>
<p><br>Buscadores para universitarios, sin registros.</p>
	<ul>
		<li><p><a href="/buscar_empresa/">Buscador de empresas</a></p></li>
		<li><p><a href="/buscar_zona/">Buscador por zona</a></p></li>
		<li><p><a href="/buscar_tematica/">Buscador por tematica</a></p></li>
	</ul>
{% endblock %}