Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/cursos/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings

urlpatterns = [ 
	url(r'^nuevo_curso$',views.Nuevo_curso, name="nuevo_curso"),
	url(r'^lista_cursos$',views.Lista_cursos, name="lista_cursos"),
	url(r'^detalle/(?P<curso_nombre>.*)$',views.Detalle_curso, name="detalle_curso"),
	url(r'^modificar/(?P<curso_nombre>.*)$',views.Modificar_curso, name="modificar_curso"),
	url(r'^mis_cursos/$',views.Mis_cursos, name="mis_cursos"),
	url(r'^eliminar_curso/(?P<pk>[0-9]+)/$', views.Eliminar_curso, name="eliminar_curso"),
	]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/djangoPW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^empresa/',include('empresa.urls',namespace='empresa')),
    url(r'^cursos/', include('cursos.urls', namespace='cursos')),
    url(r'^practicas/',include('practicas.urls', namespace='practicas')),
    url(r'^buscar_zona/$',views.buscar_zona, name ='buscar'),
    url(r'^buscar_zona/(?P<zona>.*)$',views.listar_zona, name='listar_zona'),
    url(r'^buscar_empresa/$',views.buscar_empresa, name='buscar_empresa'),
    url(r'^buscar_tematica/$',views.buscar_tematica, name='buscar_tematica'),
    url(r'^$',views.index, name='index'),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^registro$',views.Registro,name="registro"),
	url(r'^agregado$',views.Agregado,name="agreagado"),
	url(r'^login$',views.Login, name="login"),
	url(r'^logout$',views.Logout, name="logout"),
	url(r'^already_loged$',views.Already_loged, name="already_loged"),
	url(r'^not_loged$',views.Not_loged, name="not_loged"),
	url(r'^mi_empresa$',views.Mi_empresa, name='mi_empresa'),
	url(r'^detalle/(?P<pk>[0-9]+)/$', views.Detalle_empresa, name="detalle_empresa"),
	url(r'^modificar_mi_empresa$',views.Modificar_mi_empresa, name="modificar_mi_empresa"),
	url(r'^modificar_mi_contrasenia$',views.Cambiar_contrasenia, name="modificar_mi_contrasenia"),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/practicas/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from practicas.views import Nueva_practica
from django.contrib.auth.decorators import login_required


urlpatterns = [
	url(r'^nueva_practica$', views.Nueva_practica, name="nueva_practica"),
	url(r'^detalle/(?P<pk>[0-9]+)/$',views.Detalle_practica.as_view(), name="detalle_practica"),
	url(r'^lista_practicas$', views.Lista_practicas.as_view(), name="lista_practicas"),
	url(r'^modificar/(?P<pk>[0-9]+)/$',login_required(views.Modificar_practica), name="modificar_practica"),
	url(r'^mis_practicas$', login_required(views.Mis_practicas.as_view()), name="mis_practicas"),
	url(r'^eliminar_practica/(?P<pk>[0-9]+)/$',views.Eliminar_practica, name="eliminar_practica"),
]

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

from django.utils.encoding import python_2_unicode_compatible

# Create your models here.



@python_2_unicode_compatible
class Empresa(User):
	telefono=models.CharField(null=False, max_length=9)
	nombre=models.CharField(unique=True, max_length=30)
	descripcion=models.TextField(blank=True)
	def __str__(self):
		return self.nombre

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/views.py
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from .models import Empresa
from cursos.models import Curso
from practicas.models import Practica
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from empresa.form import EmpresaResgisterForm, EmpresaLoginForm, ModificarEmpresaForm,CambiarContraseniaForm
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required


# Create your views here.

def Registro(request):
	if request.user.is_authenticated():
		return HttpResponse("Ya estas registrado")
	else:
		if request.method == 'POST':
			form = EmpresaResgisterForm(request.POST,request.FILES)
			if form.is_valid():
				form.save()
				return redirect("/empresa/agregado")
		else:
			form = EmpresaResgisterForm()
		context = {'form':form}
		return render(request,'empresa/RegistroEmpresa.html',context) 

def Agregado(request):
	return render(request, 'empresa/Agregado.html')

def Login(request):
	if request.user.is_authenticated():
		return redirect("/empresa/already_loged")
	else:
		if request.method == 'POST':
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect("/empresa/mi_empresa")
			else:
				return redirect("/empresa/login")
		else:
			form = EmpresaLoginForm()
		context = {'form':form}
		return render(request,'empresa/LoginEmpresa.html',context)

def Logout(request):
	if request.user.is_authenticated():
		logout(request)
		return render(request, "empresa/Logout.html")
	else:
		return redirect("/empresa/not_loged")

def Already_loged(request):
	return render(request,"empresa/Already_loged.html")
def Not_loged(request):
	return render(request,"empresa/Not_loged.html")

@login_required()
def Mi_empresa(request):
	empresa = get_object_or_404(Empresa, username=request.user.get_username())
	mis_cursos = Curso.objects.filter(empresa=empresa)
	mis_practicas = Practica.objects.filter(empresa=empresa)
	context={"empresa":empresa,"mis_cursos":mis_cursos, "mis_practicas":mis_practicas}
	return render(request,"empresa/Mi_empresa.html",context)

@login_required()
def Modificar_mi_empresa(request):
	empresa=get_object_or_404(Empresa, username=request.user.get_username())
	if request.method == 'POST':
		form = ModificarEmpresaForm(request.POST, instance=empresa)
		if form.is_valid():
			form.save()
			return redirect("/empresa/mi_empresa")
	else:
		form= ModificarEmpresaForm(instance=empresa)
	context={'form':form, 'empresa':empresa}
	return render(request, 'empresa/Modificar_empresa_form.html',context)

@login_required()
def Cambiar_contrasenia(request):
	empresa=get_object_or_404(Empresa, username=request.user.get_username())
	msg = "Las dos contrasenias deben ser iguales"
	if request.method == 'POST':
		password_actual= request.POST['password_actual']
		password = request.POST['password']
		password_check = request.POST['password_check']

		if empresa.check_password(password_actual):
			if password == password_check:
				empresa.set_password(password)
				empresa.save()
				# Cuando cambiamos la contrasenia de la empresa actual se deslogea automaticamente por lo que le hacemos un login automatico
				user = authenticate(username=empresa.username, password=password)
				if user is not None:
					login(request, user)
					return redirect("/empresa/mi_empresa")
				else:
					return redirect("/empresa/login")
				
			else:
				msg = "Las contrasenias no coinciden"
				form = CambiarContraseniaForm()
		else:
			msg = "Esa no es su contrasenia actual"
			form = CambiarContraseniaForm()
	else:
		form = CambiarContraseniaForm()
	context={'msg':msg,'form':form}
	return render(request, "empresa/Cambiar_contrasenia_form.html",context)



def Detalle_empresa(request,pk):
	empresa=get_object_or_404(Empresa, pk=pk)
	lista_cursos=Curso.objects.filter(empresa=empresa)
	lista_practicas=Practica.objects.filter(empresa=empresa)
	context={'empresa':empresa ,'lista_cursos':lista_cursos, 'lista_practicas':lista_practicas}
	return render(request,"empresa/Detalle_empresa_publico.html",context)

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Agregado.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}Empresa agregada con exito{% endblock %}
{% block empresasUser %}Puede continuar su visita por la pagina{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Already_loged.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}Ya estas logeado{% endblock %}
{% block empresasUser %}Puede continuar su visita por la pagina{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Cambiar_contrasenia_form.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}
<p>{{msg}}</p>
<form id="form" method="POST"  enctype="multipart/form-data">{% csrf_token %}
{{form.as_p}}
<input type="submit" name="Submit">
	
</form>


{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Detalle_empresa_publico.html
{% extends "baseTemplateEmpresa.html" %}

{% block title %}{{empresa.nombre}}{% endblock %}

{% block mainText %}
Informacion publica de la empresa:

<p>Nombre: {{empresa.nombre}}</p>
<p>Descripcion: {{empresa.descripcion}}</p>
<p>Telefono de contacto: {{empresa.telefono}} </p>
<p>Email: {{empresa.email}}</p>

<p>Cursos:</p>
{% if lista_cursos|length %}
	{% for curso in lista_cursos %}
		<ul><a href="{% url 'cursos:detalle_curso' curso.nombre %}">{{curso.nombre}}</a></ul>
	{% endfor %}
{% else %}
	<p>No ofertamos cursos</p>
{% endif %}

<p>Practicas:</p>
{% if lista_practicas|length %}
	{% for practica in lista_practicas %}
		<ul><a href="{% url 'practicas:detalle_practica' practica.pk %}">{{practica.nombre}}</a></ul>
	{% endfor %}
{% else %}
	<p>No ofertamos practicas</p>
{% endif %}





{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/LoginEmpresa.html
{% extends "baseTemplateEmpresa.html" %}

{% block tittle %}Login{% endblock %}

{% block mainText %}
	<p>
	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
		{{ form.as_p }}
		<p><input type="submit" name="Submit"></p>
	</form>


	</p>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Logout.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}Logout correcto{% endblock %}
{% block empresasUser %}Puede continuar su visita por la pagina{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Mi_empresa.html
{% extends "baseTemplateEmpresa.html" %}

{% block title %}{{empresa.nombre}}{% endblock %}

{% block mainText %}
<p>Nombre público: {{empresa.nombre}}</p>
<p>Descripcion: {{empresa.descripcion}}</p>
<p>Username: {{empresa.username}}</p>
<p>Telefono: {{empresa.telefono}}</p>
<p>Email: {{empresa.email}}</p>


<p><br><a href="{% url 'empresa:modificar_mi_empresa' %}">Modificar datos</a></p>
<p><a href="{% url 'empresa:modificar_mi_contrasenia' %}">Cambiar contrasenia</a><br></p>


<p><br>Estos son los servicios que ofrece:<br></p>
{% if mis_cursos %}
	<p><a href="/cursos/mis_cursos">Mis cursos:</a></p>
	{% for curso in mis_cursos %}
		<ul>{{curso.nombre}}: {{curso.descripcion}}</ul>
	{% endfor %}

{% else %}
	<br>No tienes cursos actualmente.
{% endif %}


{% if mis_practicas %}
	<p><a href="/practicas/mis_practicas">Mis practicas:</a></p>
	{% for practica in mis_practicas %}
		<ul>{{practica.nombre}}: {{practica.descripcion}}</ul>
	{% endfor %}
{% else %}
	<br>No tienes practicas actualmente

{% endif %}

<p><br>Añada nuevos servicios:<br></p>
<ul><a href="{% url 'cursos:nuevo_curso' %}">Añadir curso</a></ul>
<ul><a href="{% url 'practicas:nueva_practica' %}">Añadir practica</a></ul>	

{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Modificar_contrasenia_form.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}
<p>{{msg}}</p>
<form id="form" method="POST"  enctype="multipart/form-data">{% csrf_token %}
{{form.as_p}}
<input type="submit" name="Submit">
	
</form>


{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Modificar_empresa_form.html
{% extends 'baseTemplateEmpresa.html' %}
{% block mainText %}

<h1>Modificando {{empresa.nombre}}</h1>

<form id='form' method="POST" enctype="multipart/form-data">{% csrf_token %}
	{{form.as_p}}
	<input type="submit" name="Modificar">
</form>




{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/Not_loged.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}No estas logeado{% endblock %}
{% block empresasUser %}Puede continuar su visita por la pagina{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/RegistroEmpresa.html
{% extends "baseTemplateEmpresa.html" %}

{% block title %}Registro de nueva empresa{% endblock %}

{% block mainText %}
	<p>
	<form id='form' method='POST' enctype="multipart/form-data" action="">{% csrf_token %}
			{{form.as_p}}
			<p><input type="submit" value='Submit'></p>
	</form>
	</p>
{% endblock %}

Primer_cuatrimestre/PW/Trabajo/entregables/09-01-2017-gestor/djangoPW/empresa/templates/empresa/loged.html
{% extends "baseTemplateEmpresa.html" %}

{% block mainText %}Se ha logueado correctamente{% endblock %}
{% block empresasUser %}Puede continuar su visita por la pagina{% endblock %}